### ISSUE TITLE
Getting Error about Valheim Password

### ISSUE THREAD

**Issue by BenSanders** [0n1udra/slime_server#13]
Trying to start this up for a Minecraft server but seeing errors about valheim passwords?

```
Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 946, in _load_from_module_spec
    await setup(self)
  File "/opt/MoralBot/slime_server-master/source/cogs/personal.py", line 332, in setup
    await bot.add_cog(Other_Games(bot))
  File "/opt/MoralBot/slime_server-master/source/cogs/personal.py", line 66, in __init__
    self.valheim_text = f"{self.ip_text}\nPass: `{slime_vars.valheim_password}`"
AttributeError: module 'slime_vars' has no attribute 'valheim_password'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/opt/MoralBot/slime_server-master/source/bot_files/slime_bot.py", line 24, in on_ready
    await setup(bot)
  File "/opt/MoralBot/slime_server-master/source/bot_files/slime_bot.py", line 479, in setup
    await bot.load_extension(f"cogs.{i[:-3]}")
  File "/home/ben/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/home/ben/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 951, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.personal' raised an error: AttributeError: module 'slime_vars' has no attribute 'valheim_password'
```

**Comment by BenSanders** [comment]
To add a little more I'm running this on Debian 11 in `/opt/MoralBot` with a vanilla Minecraft server running in `/opt/minecraft/` as a systemd service.

**Comment by BenSanders** [comment]
Realized I could have included this bit at the beginning of running the bot
```
python3 run_bot.py starttmux startboth attachtmux
[2023-01-29 21:20:09] (backend_functions.py): Server selected: papermc
sh: 1: tmux: not found
[2023-01-29 21:20:09] (run_bot.py): ERROR: Starting tmux session
sh: 1: tmux: not found
[2023-01-29 21:20:09] (run_bot.py): ERROR: Creating second tmux panes
sh: 1: tmux: not found
sh: 1: tmux: not found
sh: 1: tmux: not found
[2023-01-29 21:20:11] (run_bot.py): ERROR: Changing directory (/home/ben/MoralBot/slime_server-master/source)
[2023-01-29 21:20:11] (run_bot.py): INFO: Using token: /home/ben/MoralBot/keys/slime_server.token
2023-01-29 21:20:11 INFO     discord.client logging in using static token
2023-01-29 21:20:12 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 8266958bf63574dd70af6593310aec57).
2023-01-29 21:20:14 ERROR    discord.client Ignoring exception in on_ready
```

**Comment by 0n1udra** [comment]
oops my mistake. I have a personal branch for my own specific setup. Some of the code ended up on the main branch. It should be fixed if you git pull the latest code (e267b09afe10fd2ac1a7c2f0fb38ce70d3a69432)

**Comment by BenSanders** [comment]
Awesome, thank you!

**Comment by 0n1udra** [comment]
Let me know if it works. I would need more information on how you are running the Minecraft server. For now the easiest would be using tmux. You can also use the subprocess method or using RCON. Do note if you use the subprocess method, if the bot dies, the Minecraft server process will also. imo tmux is the best route

**Comment by BenSanders** [comment]
Will do I was using the process here https://www.shells.com/l/en-US/tutorial/0-A-Guide-to-Installing-a-Minecraft-Server-on-Linux-Ubuntu

That said though I'll let you know if it does work and if not I'll give it a try using tmux instead.

**Comment by BenSanders** [comment]
So, I decided to stop the systemd service and go the tmux route but seeing.
```
python3 run_bot.py starttmux startboth attachtmux
[2023-01-29 23:18:25] (backend_functions.py): Server selected: papermc
[2023-01-29 23:18:25] (run_bot.py): INFO: Started Tmux detached session
[2023-01-29 23:18:25] (run_bot.py): INFO: Created second tmux panes
can't find pane: 6
[2023-01-29 23:18:27] (run_bot.py): ERROR: Changing directory (/home/ben/MoralBot/slime_server-master/source)
[2023-01-29 23:18:27] (run_bot.py): INFO: Using token: /home/ben/keys/slime_server.token
```

Then later down I see
```
[2023-01-29 23:18:30] (None): Server Status: Inactive
2023-01-29 23:18:30 ERROR    discord.client Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/ben/MoralBot/slime_server-master/source/bot_files/slime_bot.py", line 34, in on_ready
    await channel.send(f':white_check_mark: v{__version__} **Bot PRIMED** {datetime.datetime.now().strftime("%X")}')
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by 0n1udra** [comment]
:( some code was still left over from that other branch. In slime_vars.py on line 35 and 36 you set what tmux panes it will create and use. To create a tmux session just for the bot and the mc server you only need to set it to 0.0 for 'tmux_bot_pane' and 0.1 for 'tmux_minecraft_pane'. Which means the discord bot will be in tmux pane 0.0 and the minecraft server will run in tmux pane 0.1. I have it like this incase someone wanted to implement this bot into an already existing tmux session environment. E.g. I have a tmux session with 6+ panes, this so you can choose what pane you want the bot and mc server running in. However if you are just creating a new tmux session with only 2 panes just for this, you will want it set to 0.0 and 0.1. Hopefully this makes sense.
I updated the code here: (5c0a0a4cb0754c8c0fc11e56e5b03fa38c3be3e3)

I have on my to do list to create a easier setup script for this bot instead of having you set the variables manually in slime_vars.py.

**Comment by BenSanders** [comment]
Yeah, I'm thinking the NoneType object also has to do with discord.py.
One thing different I did do initially was instead of using `python -m venv ~/pyenvs/slime_server`
I used `python3 -m venv ~/pyenvs/slime_server`

The bot will respond and shows as online in my Discord server though.

**Comment by BenSanders** [comment]
haha it turns out I I forgot to use `?setchannel`.
Got so engrossed in looking at the code forgot about the final couple of steps.

Still having an issue Creating the server though from within Discord for some reason though. :/

**Comment by BenSanders** [comment]
Update: ahh just had to create the directory `~/minecraft/servers/papermc/` 
I think it's going to work now! :D 

Thank you for all your help btw. I fully didn't expect a response let alone any fixes so quickly. :)

**Comment by BenSanders** [comment]
Sorry, one final question.
Is the bot not supposed to download the jar for papermc or vanilla?

**Comment by 0n1udra** [comment]
Sorry for the lack of documentation. I have not been updating this for awhile. This has been very useful as feedback :)

You can try this
if the bot is working, use `?panel`. Set 'Mode' to 'Servers'. Use the 'New' button. 
NOTE: Make sure you have either 'vanilla' or 'papermc' in the 'SERVER NAME' field if you want to use the built it jar downloader.
This will change later, I'm updating the code so you can code in your own downloader specific for you server. Like if your using papermc, vanilla, bukkit, etc. idk if there's a easier way to get the .jars from the web, i've been just using web scraping. I only have papermc and vanilla working. 

After creating a new server in the bot, you can use `?updateserver`. This will download the latest .jar file, and also update the eula if first time.

![image](https://user-images.githubusercontent.com/15573136/215366537-9e148572-abd8-4866-94b7-51de356efe93.png)

**Comment by BenSanders** [comment]
Glad I could provide useful feedback! :)

I see now it is downloading when naming the server `papermc`. I tried naming it `Test Server` 😆 
As a side note I'm currently learning Python myself so maybe I can better understand the actual code myself someday.

**Comment by BenSanders** [comment]
hmm the weird thing is by the time the server starts up the bot times out.

**Comment by BenSanders** [comment]
The bot  would start up and start pinging for the server but then by the time the server got up the shared ID would disconnect. 

Ended up deleting the vps to start over fresh.
