### ISSUE TITLE
meError: name 'server_ip' is not defined

### ISSUE THREAD

**Issue by HDProduction010** [0n1udra/slime_server#5]
Traceback (most recent call last):
  File "/root/pyenvs/slime_server/lib/python3.8/site-packages/discord/ext/comman ds/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/root/pyenvs/slime_server/lib/python3.8/site-packages/discord/ext/comman ds/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/pyenvs/slime_server/lib/python3.8/site-packages/discord/ext/comman ds/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Nam eError: name 'server_ip' is not defined

This is the error I am getting The VARS are filled correctly. Not sure why this is failing.

**Comment by 0n1udra** [comment]
I'm guessing you are using RCON (if not try disabling that in slime_vars), I updated the code, try using the latest commit (48976a888ab947c44d022b5fe06f71c918d5a78f) and see if that works.

**Comment by HDProduction010** [comment]
I was trying a lot of things but yes I was trying to use RCON. This is also not running on the server itself it is running on the backend of a pterodactyl server on another server. Just trying to connect the two together.

**Comment by HDProduction010** [comment]
That worked thank you for your help!
